### PR TITLE
Namespace jquery events

### LINKED ISSUE #127: Using jQuery makes all events disappear when nod.remove is used
When using nod alongside jQuery, I noticed that the following lines of code don't work as well as they should:
```
function dispose () {
    element.removeEventListener('input', changed, false);
    element.removeEventListener('change', changed, false);
    element.removeEventListener('blur', changed, false);

    if ($element) {
        $element.off();
    }

    if (triggerEvents) {
        triggerEvents.forEach(function (eventName) {
            element.removeEventListener(eventName, changed, false);
        });
    }
}
```

When events are removed this way, all other event handlers I may have put on the element will also be removed.

A possible solution might be to use [jQuery namespaced events](http://api.jquery.com/event.namespace/)

### PR DESCRIPTION
**Pull request by chall8908**
Fixes #127.

In the process, I noticed one of the tests was throwing an error during cleanup (in Chrome, anyway) so I fixed it too.

### CODE REVIEW

**Comment by casperin** [comment]
You're a saviour!

I changed it so it merges into `develop` (that I just created) instead, so I can do a "proper" release later; updating the version number and such.

Thanks a lot Chris. :)

**Comment by chall8908** [comment]
No problem.  I've felt pretty bad for just dropping off the face of the planet...

**Comment by casperin** [comment]
Naaah, don't. Life moves on. :-)

I see you're into Ruby. Did you have a look at Elixir? I had a short fling with Golang, but I'm seriously considering picking Elixir up now.

**Comment by chall8908** [comment]
I have taken a look at Elixir.  It's probably one of the coolest languages I've picked up recently and I really wish I could use it more.

**Comment by casperin** [comment]
Yeah. At least around here I don't think any companies are using Elixir. No wonder though.. the language is newer than most companies. :-P

I wish JS would have pattern matching and tail call optimisation. That stuff is godly.

**Pull request merged**
